obj-y += beacon.o
obj-y += cJSON.o
obj-y += comm_gateway.o
obj-y += IRdev.o
obj-y += itach_cmd.o
obj-y += itach.o
#obj-y += itach_http.o
obj-y += public_opr.o
obj-y += status_file.o
obj-y += scanning_itachs.o


